const BASE_URL = "http://herbal.techiecy.com/"
export const BANNER_API = BASE_URL + 'banner/view/';
export const PRODUCTLIST_API = BASE_URL + 'product/item/';
export const CATEGORYLIST_API = BASE_URL +'product/category/';
export const UNITLIST_API = BASE_URL + 'product/unit/';
export const DASHBOARD = BASE_URL + 'product/dashboard/';
export const CART_API = BASE_URL + 'order/cart/';
export const Login_API = BASE_URL + 'auth/login/';
export const VERIFYOTP_API = BASE_URL + 'auth/verify_otp/';
export const ABOUT_CONTACT_API = BASE_URL + 'auth/about_us/';
